{% set name = "trio" %}
{% set version = "0.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 150f29ec923bcd51231e1d4c71c7006e65247d68759dd1c19af4ea815a25806b
  # Ignore deprecation warnings from test dependencies (pyOpenSSL/trustme) that block test collection
  patches:
    - patches/filterwarnings.patch

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=77
    - wheel
  run:
    - python
    - attrs >=23.2.0
    - cffi >=1.14  # [win]
    - idna
    - outcome
    - sniffio >=1.3.0
    - sortedcontainers
    - exceptiongroup  # [py<311]

test:
  source_files:
    - pyproject.toml
  imports:
    - trio
    - trio._channel
    - trio._core
    - trio._dtls
    - trio._file_io
    - trio._highlevel_open_tcp_stream
    - trio._highlevel_open_unix_stream
    - trio._repl
    - trio._socket
    - trio._ssl
    - trio._tests
    - trio._tools
    - trio._util
    - trio.abc
    - trio.lowlevel
    - trio.socket
    - trio.testing
    - trio.to_thread
  requires:
    - pip
    - pytest >=8.4
    - async_generator >=1.9
    - astor
    - isort
    - pyopenssl >= 22.0.0  # for the ssl + DTLS tests
    - trustme  # for the ssl + DTLS tests
    - ruff
    - black
    - pyyaml
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Skip test_dtls.py because it raises a DeprecationWarning: Attempting to mutate a Context after a Connection was created. In the future, this will raise an exception
    - python -m pytest --pyargs trio -ra -v --durations=10 -k "not slow and not redistributors_should_skip" --skip-optional-imports --disable-warnings --deselect=_tests/test_dtls.py

about:
  home: https://github.com/python-trio/trio
  license: MIT AND Apache-2.0
  license_family: Other
  license_file:
    - LICENSE.APACHE2
    - LICENSE.MIT
    - LICENSE
  summary: A friendly Python library for async concurrency and I/O
  description: |
    The Trio project aims to produce a production-quality, permissively licensed,
    async/await-native I/O library for Python.
  doc_url: https://trio.readthedocs.io
  dev_url: https://github.com/python-trio/trio

extra:
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
