{% set name = "trio" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trio-{{ version }}.tar.gz
  sha256: ffa09a74a6bf81b84f8613909fb0beaee84757450183a7a2e0b47b455c0cac5d

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - attrs >=20.1.0
    - cffi >=1.14  # [win]
    - idna
    - outcome
    - sniffio >=1.3.0
    - sortedcontainers
    - exceptiongroup # [py<311]

test:
  source_files:
    - pyproject.toml
  imports:
    - trio
    - trio.testing
  requires:
    - pip
    - pytest
    - async_generator >= 1.9
    - astor
    - isort
    - pyopenssl >= 22.0.0   # for the ssl + DTLS tests
    - trustme               # for the ssl + DTLS tests
  commands:
    - pip check
    - python -m pytest --pyargs trio -ra --durations=10 -m "not redistributors_should_skip" --skip-optional-imports

about:
  home: https://github.com/python-trio/trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Trio – a friendly Python library for async concurrency and I/O
  description: |
    The Trio project aims to produce a production-quality, permissively licensed, 
    async/await-native I/O library for Python.
  doc_url: https://trio.readthedocs.io/
  dev_url: https://github.com/python-trio/trio

extra:
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
