travis:
  secure:
    BINSTAR_TOKEN: CsZvyvPr244NIHDD9Gc5B04tZMzphxjB7f+XNvJE/qLRxFsi1MxRihk10D9taOIpev4MAn34RRSm95HR9YeEsvxhQBHjpN6oLgZJgYQC/kGzb78L/hnrQr7/4VFR92ggpikLwO4MuVvDfkrjA/mV3U58l7BVX176aJvTzNdUAg2uzYAtU4pjenAqolFVm9jac5D8V0qF470yTdcpEawxejc0uHTnHsoR9X22a7hbz4bRLzXmL0yQ4ed13wjShvaVVlPfSRnMurF86Q2bThihknv+Vs50sK7e6BaPeIgo/QWhqchuzNQVHgIizzl2VLZZLrkcfd/sF44QxvjbHNZsiOyetG8/UV223CUXPPxlEF1HfhFYogVd75An9UNIvDZ97tqgaJLmmO85bZs8hQd9svQJkTRWxLdACUrDWDb2k/TYoYis+71RQBq2OBON+JDYdGFtH16rQhpfopFu3JEaaQ8+3xdIJNokbQ+AVF/YbjkNRrhikfJEIG2leWjZ7OX4HucHDMD21A8oLmBahIQU4YUJHrsbkH4GCWh3zQw2fM3Imw5PcEaAz79JBSg5LyE3gwj9VcPuarpLJj/iLG70qrqpGUSulBC9+l3cXFoGC4IIpkhq5ZQoNz+Es566pU0YjEVXNCfSxlZtgFN9oixXfRQShB2V70XG2N5GdtjVkKc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
