travis:
  secure:
    BINSTAR_TOKEN: vZwWXl0iEMRSOzg8DZSmY9/uv8v87sVyt7wDOl+gXyZEgqSSjB+LG+x26tNueYT9hm+k9YlyYiLh3S5IFeKkoKGiqDrDnYID2nxvcApXTlZFqQbjeD4HauN+o5Q8eMDgKhb25fdqD88BtwE8oouxJ5A4bhPem2i54SeBoo+0qP9Pt3UHScUWuJYEFeARgXesVetK/Eb/njqlv7uO0pFuXgYHuLg+KJjrM++eVhLKjd+/R/nAjV+l6IPsm/wclPVH4li6Oi0ayvGTT7eDd902VjLTQNtkDe2O/vE+9jIr/jpXS8P1Rj5cUEud/p/vSpLsmkgWqF8NH3TTYWQb+zCt3jN3IFEfpCkuSBXtWsGJHfJ9nzjbGTWuBKIvE+fSyef7uPeAWxFWLeXpDRgbt6ztvRBwM9vAYRs6h2WBMP1dgMhsUgbfdG2vhp5q3x6GiHu1ilgIszGnXktoxOllsCk1EKsX0kaLETX9lEYUjQ4irdCl0eYZmc2jVsz87REv0Tj95IVxNtRcN6WmiH2bJmDcK22Urd8np7TWVTYRpeNYPbDOYPIvinOyqOi2cTcNbw1zOxpcsg4IaYp1pzMqweWzgJ67h/ASKgMkiukfGnfomquUNoBw0lFW+jgaENrwOHt4BETF0lH3kPCJ4dp2dwrt8t67PcK9u0B08Z0sGOZ9Dq4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
